"""Concrete infrastructure adapters."""

from rundra.adapters.apptainer import (
    ApptainerConfigurationError,
    ApptainerRuntime,
    ApptainerRuntimeError,
    ApptainerUnavailableError,
    RemoteApptainerRuntime,
)
from rundra.adapters.htcondor import (
    HTCondorCancellationError,
    HTCondorQueryError,
    HTCondorScheduler,
    HTCondorSchedulerError,
    HTCondorScriptError,
    HTCondorSubmissionError,
    render_condor_array_submit,
    render_condor_submit,
    validate_htcondor_resources,
)
from rundra.adapters.local import (
    LocalScheduler,
    LocalSchedulerError,
    LocalStager,
    LocalStagerError,
    LocalTransport,
    LocalTransportError,
    WorkspaceCollisionError,
)
from rundra.adapters.native import NativeRuntime, NativeRuntimeError
from rundra.adapters.pbs import (
    OpenPBSScheduler,
    PBSCancellationError,
    PBSQueryError,
    PBSSchedulerError,
    PBSScriptError,
    PBSSubmissionError,
    render_qsub_array_script,
    render_qsub_script,
    validate_pbs_resources,
)
from rundra.adapters.preflight import RemotePreflight
from rundra.adapters.purge import LocalPurger, PurgeError, SSHPurger
from rundra.adapters.remote import (
    RemoteWorkspaceAllocator,
    RemoteWorkspaceCollisionError,
    RemoteWorkspaceError,
)
from rundra.adapters.rsync import (
    RsyncRetrievalError,
    RsyncStager,
    RsyncStagerError,
    RsyncUnavailableError,
    RsyncUploadError,
)
from rundra.adapters.shared import SharedStager, SharedStagerError
from rundra.adapters.slurm import (
    SlurmArrayRequest,
    SlurmCancellationError,
    SlurmQueryError,
    SlurmScheduler,
    SlurmScriptError,
    SlurmSubmissionError,
    render_sbatch_array_script,
    render_sbatch_script,
    render_slurm_array_manifest,
    render_slurm_compact_bundle_manifest,
    validate_slurm_resources,
)
from rundra.adapters.ssh import (
    SSHCommandError,
    SSHExecutionError,
    SSHTransport,
    SSHTransportError,
    SSHUnavailableError,
)

__all__ = [
    "ApptainerConfigurationError",
    "ApptainerRuntime",
    "ApptainerRuntimeError",
    "ApptainerUnavailableError",
    "LocalScheduler",
    "HTCondorCancellationError",
    "HTCondorQueryError",
    "HTCondorScheduler",
    "HTCondorSchedulerError",
    "HTCondorScriptError",
    "HTCondorSubmissionError",
    "LocalSchedulerError",
    "LocalStager",
    "LocalStagerError",
    "LocalTransport",
    "LocalTransportError",
    "LocalPurger",
    "NativeRuntime",
    "NativeRuntimeError",
    "OpenPBSScheduler",
    "PBSCancellationError",
    "PBSQueryError",
    "PBSSchedulerError",
    "PBSScriptError",
    "PBSSubmissionError",
    "RemoteWorkspaceAllocator",
    "RemoteApptainerRuntime",
    "RemoteWorkspaceCollisionError",
    "RemoteWorkspaceError",
    "RemotePreflight",
    "RsyncStager",
    "RsyncStagerError",
    "RsyncRetrievalError",
    "RsyncUnavailableError",
    "RsyncUploadError",
    "PurgeError",
    "SSHCommandError",
    "SSHExecutionError",
    "SSHTransport",
    "SSHTransportError",
    "SSHUnavailableError",
    "SSHPurger",
    "SharedStager",
    "SharedStagerError",
    "SlurmArrayRequest",
    "SlurmCancellationError",
    "SlurmQueryError",
    "SlurmScheduler",
    "SlurmScriptError",
    "SlurmSubmissionError",
    "WorkspaceCollisionError",
    "render_sbatch_array_script",
    "render_sbatch_script",
    "render_slurm_array_manifest",
    "render_slurm_compact_bundle_manifest",
    "render_qsub_array_script",
    "render_qsub_script",
    "validate_pbs_resources",
    "render_condor_array_submit",
    "render_condor_submit",
    "validate_htcondor_resources",
    "validate_slurm_resources",
]
