ARG BASE_IMAGE=rundra-slurm-system:local
FROM ${BASE_IMAGE}

USER root
COPY cgroup-entrypoint.sh /opt/rundra-cluster/cgroup-entrypoint.sh
RUN chmod 0755 /opt/rundra-cluster/cgroup-entrypoint.sh
ENTRYPOINT ["/opt/rundra-cluster/cgroup-entrypoint.sh"]
